name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: nvidia/cuda:12.0.0-devel-ubuntu22.04
      # Remove GPU options since GitHub Actions doesn't support GPU

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y cmake g++ python3-dev python3-pip git
        python3 -m pip install pybind11 pytest numpy

    # Set environment variable to indicate we're in CI without GPU
    - name: Set CI environment
      run: echo "CI_NO_GPU=1" >> $GITHUB_ENV

    - name: Build
      run: |
        chmod +x scripts/build.sh
        ./scripts/build.sh

    - name: Test C++
      run: |
        chmod +x scripts/test.sh
        ./build/backend/test_arima

    - name: Test Python
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)/frontend
        python3 -m pytest frontend/tests/

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 frontend/ --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 frontend/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics